# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mrMainWindow.ui'
#
# Created: Thu Nov 22 21:04:15 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(755, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.gridLayout_2.addWidget(self.mdiArea, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuStop = QtGui.QMenu(self.menubar)
        self.menuStop.setObjectName(_fromUtf8("menuStop"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionRun_All_Record = QtGui.QAction(MainWindow)
        self.actionRun_All_Record.setObjectName(_fromUtf8("actionRun_All_Record"))
        self.actionRun_Key_Record = QtGui.QAction(MainWindow)
        self.actionRun_Key_Record.setObjectName(_fromUtf8("actionRun_Key_Record"))
        self.actionRun_Mouse_Record = QtGui.QAction(MainWindow)
        self.actionRun_Mouse_Record.setObjectName(_fromUtf8("actionRun_Mouse_Record"))
        self.actionStop_All_Record = QtGui.QAction(MainWindow)
        self.actionStop_All_Record.setEnabled(False)
        self.actionStop_All_Record.setObjectName(_fromUtf8("actionStop_All_Record"))
        self.actionStop_Key_Record = QtGui.QAction(MainWindow)
        self.actionStop_Key_Record.setEnabled(False)
        self.actionStop_Key_Record.setObjectName(_fromUtf8("actionStop_Key_Record"))
        self.actionStop_Mouse_Record = QtGui.QAction(MainWindow)
        self.actionStop_Mouse_Record.setEnabled(False)
        self.actionStop_Mouse_Record.setObjectName(_fromUtf8("actionStop_Mouse_Record"))
        self.actionAbout_Me = QtGui.QAction(MainWindow)
        self.actionAbout_Me.setObjectName(_fromUtf8("actionAbout_Me"))
        self.actionVersion = QtGui.QAction(MainWindow)
        self.actionVersion.setObjectName(_fromUtf8("actionVersion"))
        self.actionKeyboard_Table = QtGui.QAction(MainWindow)
        self.actionKeyboard_Table.setObjectName(_fromUtf8("actionKeyboard_Table"))
        self.actionMouse_Table = QtGui.QAction(MainWindow)
        self.actionMouse_Table.setObjectName(_fromUtf8("actionMouse_Table"))
        self.actionReset_Inputs = QtGui.QAction(MainWindow)
        self.actionReset_Inputs.setObjectName(_fromUtf8("actionReset_Inputs"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset_Inputs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRun.addAction(self.actionRun_All_Record)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionRun_Key_Record)
        self.menuRun.addAction(self.actionRun_Mouse_Record)
        self.menuStop.addAction(self.actionStop_All_Record)
        self.menuStop.addSeparator()
        self.menuStop.addAction(self.actionStop_Key_Record)
        self.menuStop.addAction(self.actionStop_Mouse_Record)
        self.menuAbout.addAction(self.actionAbout_Me)
        self.menuAbout.addAction(self.actionVersion)
        self.menuDisplay.addAction(self.actionKeyboard_Table)
        self.menuDisplay.addAction(self.actionMouse_Table)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuStop.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRun.setTitle(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStop.setTitle(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDisplay.setTitle(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_All_Record.setText(QtGui.QApplication.translate("MainWindow", "Run All Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Key_Record.setText(QtGui.QApplication.translate("MainWindow", "Run Key Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Mouse_Record.setText(QtGui.QApplication.translate("MainWindow", "Run Mouse Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_All_Record.setText(QtGui.QApplication.translate("MainWindow", "Stop All Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Key_Record.setText(QtGui.QApplication.translate("MainWindow", "Stop Key Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Mouse_Record.setText(QtGui.QApplication.translate("MainWindow", "Stop Mouse Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Me.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVersion.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyboard_Table.setText(QtGui.QApplication.translate("MainWindow", "Keyboard Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMouse_Table.setText(QtGui.QApplication.translate("MainWindow", "Mouse Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Inputs.setText(QtGui.QApplication.translate("MainWindow", "Reset Inputs", None, QtGui.QApplication.UnicodeUTF8))

import res.res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

