# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mrMainWindow.ui'
#
# Created: Sun Dec 09 20:44:28 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(713, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.gridLayout_2.addWidget(self.mdiArea, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 6, 6, 6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.KeyTab = QtGui.QWidget()
        self.KeyTab.setObjectName(_fromUtf8("KeyTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.KeyTab)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.KeyTabLayout = QtGui.QGridLayout()
        self.KeyTabLayout.setObjectName(_fromUtf8("KeyTabLayout"))
        self.gridLayout_7.addLayout(self.KeyTabLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.KeyTab, icon, _fromUtf8(""))
        self.MouseTab = QtGui.QWidget()
        self.MouseTab.setObjectName(_fromUtf8("MouseTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.MouseTab)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.MouseTabLayout = QtGui.QGridLayout()
        self.MouseTabLayout.setObjectName(_fromUtf8("MouseTabLayout"))
        self.gridLayout_6.addLayout(self.MouseTabLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.MouseTab, icon, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupGlobalStats = QtGui.QGroupBox(self.centralwidget)
        self.groupGlobalStats.setMinimumSize(QtCore.QSize(0, 245))
        self.groupGlobalStats.setObjectName(_fromUtf8("groupGlobalStats"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupGlobalStats)
        self.gridLayout_3.setContentsMargins(5, 2, 5, 5)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupKeyStats = QtGui.QGroupBox(self.groupGlobalStats)
        self.groupKeyStats.setObjectName(_fromUtf8("groupKeyStats"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupKeyStats)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.TotKeyPressLabel = QtGui.QLabel(self.groupKeyStats)
        self.TotKeyPressLabel.setObjectName(_fromUtf8("TotKeyPressLabel"))
        self.gridLayout_4.addWidget(self.TotKeyPressLabel, 0, 0, 1, 1)
        self.TotKeyReleasedLabel = QtGui.QLabel(self.groupKeyStats)
        self.TotKeyReleasedLabel.setObjectName(_fromUtf8("TotKeyReleasedLabel"))
        self.gridLayout_4.addWidget(self.TotKeyReleasedLabel, 1, 0, 1, 1)
        self.TotKeyPressValue = QtGui.QLabel(self.groupKeyStats)
        self.TotKeyPressValue.setObjectName(_fromUtf8("TotKeyPressValue"))
        self.gridLayout_4.addWidget(self.TotKeyPressValue, 0, 1, 1, 1)
        self.TotKeyReleasedValue = QtGui.QLabel(self.groupKeyStats)
        self.TotKeyReleasedValue.setObjectName(_fromUtf8("TotKeyReleasedValue"))
        self.gridLayout_4.addWidget(self.TotKeyReleasedValue, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupKeyStats)
        self.groupMouseStats = QtGui.QGroupBox(self.groupGlobalStats)
        self.groupMouseStats.setObjectName(_fromUtf8("groupMouseStats"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupMouseStats)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.TotMouseRightLabel = QtGui.QLabel(self.groupMouseStats)
        self.TotMouseRightLabel.setObjectName(_fromUtf8("TotMouseRightLabel"))
        self.gridLayout_5.addWidget(self.TotMouseRightLabel, 1, 0, 1, 1)
        self.TotMouseRightValue = QtGui.QLabel(self.groupMouseStats)
        self.TotMouseRightValue.setObjectName(_fromUtf8("TotMouseRightValue"))
        self.gridLayout_5.addWidget(self.TotMouseRightValue, 1, 1, 1, 1)
        self.TotMouseLeftLabel = QtGui.QLabel(self.groupMouseStats)
        self.TotMouseLeftLabel.setObjectName(_fromUtf8("TotMouseLeftLabel"))
        self.gridLayout_5.addWidget(self.TotMouseLeftLabel, 0, 0, 1, 1)
        self.TotMouseLeftValue = QtGui.QLabel(self.groupMouseStats)
        self.TotMouseLeftValue.setObjectName(_fromUtf8("TotMouseLeftValue"))
        self.gridLayout_5.addWidget(self.TotMouseLeftValue, 0, 1, 1, 1)
        self.TotMouseLabel = QtGui.QLabel(self.groupMouseStats)
        self.TotMouseLabel.setObjectName(_fromUtf8("TotMouseLabel"))
        self.gridLayout_5.addWidget(self.TotMouseLabel, 2, 0, 1, 1)
        self.TotMouseValue = QtGui.QLabel(self.groupMouseStats)
        self.TotMouseValue.setObjectName(_fromUtf8("TotMouseValue"))
        self.gridLayout_5.addWidget(self.TotMouseValue, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupMouseStats)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupGlobalStats)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuStop = QtGui.QMenu(self.menubar)
        self.menuStop.setObjectName(_fromUtf8("menuStop"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionRun_All_Record = QtGui.QAction(MainWindow)
        self.actionRun_All_Record.setObjectName(_fromUtf8("actionRun_All_Record"))
        self.actionRun_Key_Record = QtGui.QAction(MainWindow)
        self.actionRun_Key_Record.setObjectName(_fromUtf8("actionRun_Key_Record"))
        self.actionRun_Mouse_Record = QtGui.QAction(MainWindow)
        self.actionRun_Mouse_Record.setObjectName(_fromUtf8("actionRun_Mouse_Record"))
        self.actionStop_All_Record = QtGui.QAction(MainWindow)
        self.actionStop_All_Record.setEnabled(False)
        self.actionStop_All_Record.setObjectName(_fromUtf8("actionStop_All_Record"))
        self.actionStop_Key_Record = QtGui.QAction(MainWindow)
        self.actionStop_Key_Record.setEnabled(False)
        self.actionStop_Key_Record.setObjectName(_fromUtf8("actionStop_Key_Record"))
        self.actionStop_Mouse_Record = QtGui.QAction(MainWindow)
        self.actionStop_Mouse_Record.setEnabled(False)
        self.actionStop_Mouse_Record.setObjectName(_fromUtf8("actionStop_Mouse_Record"))
        self.actionAbout_Me = QtGui.QAction(MainWindow)
        self.actionAbout_Me.setObjectName(_fromUtf8("actionAbout_Me"))
        self.actionVersion = QtGui.QAction(MainWindow)
        self.actionVersion.setObjectName(_fromUtf8("actionVersion"))
        self.actionKeyboard_Table = QtGui.QAction(MainWindow)
        self.actionKeyboard_Table.setObjectName(_fromUtf8("actionKeyboard_Table"))
        self.actionMouse_Table = QtGui.QAction(MainWindow)
        self.actionMouse_Table.setObjectName(_fromUtf8("actionMouse_Table"))
        self.actionReset_Inputs = QtGui.QAction(MainWindow)
        self.actionReset_Inputs.setObjectName(_fromUtf8("actionReset_Inputs"))
        self.actionKeyboard_Stats = QtGui.QAction(MainWindow)
        self.actionKeyboard_Stats.setCheckable(True)
        self.actionKeyboard_Stats.setChecked(True)
        self.actionKeyboard_Stats.setObjectName(_fromUtf8("actionKeyboard_Stats"))
        self.actionMouse_Stats = QtGui.QAction(MainWindow)
        self.actionMouse_Stats.setObjectName(_fromUtf8("actionMouse_Stats"))
        self.actionKeyboard_frequency_graph = QtGui.QAction(MainWindow)
        self.actionKeyboard_frequency_graph.setCheckable(True)
        self.actionKeyboard_frequency_graph.setChecked(True)
        self.actionKeyboard_frequency_graph.setObjectName(_fromUtf8("actionKeyboard_frequency_graph"))
        self.actionMouse_frequency_graph = QtGui.QAction(MainWindow)
        self.actionMouse_frequency_graph.setCheckable(True)
        self.actionMouse_frequency_graph.setChecked(True)
        self.actionMouse_frequency_graph.setObjectName(_fromUtf8("actionMouse_frequency_graph"))
        self.actionClick_Distribution = QtGui.QAction(MainWindow)
        self.actionClick_Distribution.setCheckable(True)
        self.actionClick_Distribution.setChecked(True)
        self.actionClick_Distribution.setObjectName(_fromUtf8("actionClick_Distribution"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset_Inputs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRun.addAction(self.actionRun_All_Record)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionRun_Key_Record)
        self.menuRun.addAction(self.actionRun_Mouse_Record)
        self.menuStop.addAction(self.actionStop_All_Record)
        self.menuStop.addSeparator()
        self.menuStop.addAction(self.actionStop_Key_Record)
        self.menuStop.addAction(self.actionStop_Mouse_Record)
        self.menuAbout.addAction(self.actionAbout_Me)
        self.menuAbout.addAction(self.actionVersion)
        self.menuDisplay.addAction(self.actionKeyboard_Stats)
        self.menuDisplay.addSeparator()
        self.menuDisplay.addAction(self.actionKeyboard_frequency_graph)
        self.menuDisplay.addAction(self.actionMouse_frequency_graph)
        self.menuDisplay.addSeparator()
        self.menuDisplay.addAction(self.actionClick_Distribution)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuStop.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.KeyTab), QtGui.QApplication.translate("MainWindow", "Key Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MouseTab), QtGui.QApplication.translate("MainWindow", "Mouse Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.groupGlobalStats.setTitle(QtGui.QApplication.translate("MainWindow", "Global Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.groupKeyStats.setTitle(QtGui.QApplication.translate("MainWindow", "Keyboard", None, QtGui.QApplication.UnicodeUTF8))
        self.TotKeyPressLabel.setText(QtGui.QApplication.translate("MainWindow", "Total key pressed :", None, QtGui.QApplication.UnicodeUTF8))
        self.TotKeyReleasedLabel.setText(QtGui.QApplication.translate("MainWindow", "Total key released :", None, QtGui.QApplication.UnicodeUTF8))
        self.TotKeyPressValue.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotKeyReleasedValue.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupMouseStats.setTitle(QtGui.QApplication.translate("MainWindow", "Mouse", None, QtGui.QApplication.UnicodeUTF8))
        self.TotMouseRightLabel.setText(QtGui.QApplication.translate("MainWindow", "Total right clic :", None, QtGui.QApplication.UnicodeUTF8))
        self.TotMouseRightValue.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotMouseLeftLabel.setText(QtGui.QApplication.translate("MainWindow", "Total  left clic :", None, QtGui.QApplication.UnicodeUTF8))
        self.TotMouseLeftValue.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotMouseLabel.setText(QtGui.QApplication.translate("MainWindow", "Total clic :", None, QtGui.QApplication.UnicodeUTF8))
        self.TotMouseValue.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRun.setTitle(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStop.setTitle(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDisplay.setTitle(QtGui.QApplication.translate("MainWindow", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_All_Record.setText(QtGui.QApplication.translate("MainWindow", "Run All Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Key_Record.setText(QtGui.QApplication.translate("MainWindow", "Run Key Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Mouse_Record.setText(QtGui.QApplication.translate("MainWindow", "Run Mouse Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_All_Record.setText(QtGui.QApplication.translate("MainWindow", "Stop All Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Key_Record.setText(QtGui.QApplication.translate("MainWindow", "Stop Key Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Mouse_Record.setText(QtGui.QApplication.translate("MainWindow", "Stop Mouse Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Me.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVersion.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyboard_Table.setText(QtGui.QApplication.translate("MainWindow", "Keyboard Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMouse_Table.setText(QtGui.QApplication.translate("MainWindow", "Mouse Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Inputs.setText(QtGui.QApplication.translate("MainWindow", "Reset Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyboard_Stats.setText(QtGui.QApplication.translate("MainWindow", "Keyboard Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMouse_Stats.setText(QtGui.QApplication.translate("MainWindow", "Mouse Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyboard_frequency_graph.setText(QtGui.QApplication.translate("MainWindow", "Keyboard frequency graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMouse_frequency_graph.setText(QtGui.QApplication.translate("MainWindow", "Mouse frequency graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClick_Distribution.setText(QtGui.QApplication.translate("MainWindow", "Click Distribution", None, QtGui.QApplication.UnicodeUTF8))

import res.res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

